# Generated by Django 3.2.8 on 2022-03-25 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_bloguser_email'),
        ('posts', '0002_remove_comment_comment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_author', to='users.bloguser'),
        ),
    ]
