# Generated by Django 3.2.8 on 2022-03-31 18:18

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=cloudinary.models.CloudinaryField(default='post-placeholder', max_length=255, verbose_name='post-image'),
        ),
    ]
