# Generated by Django 3.2.8 on 2022-03-23 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_bloguser_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloguser',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='bloguser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='bloguser',
            name='profession',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
