# Generated by Django 3.2.8 on 2022-04-02 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_bloguser_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloguser',
            name='image',
        ),
    ]
