# Generated by Django 3.2.8 on 2022-03-25 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220323_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloguser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
