# Generated by Django 3.2.8 on 2022-03-31 18:00

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_bloguser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloguser',
            name='image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
