# Generated by Django 3.2.8 on 2022-03-31 18:18

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_bloguser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloguser',
            name='image',
            field=cloudinary.models.CloudinaryField(default='profile-placeholder', max_length=255, verbose_name='profile-image'),
        ),
    ]
